# Numpy - Numerical Python

## 1. ndarray(Numpy Dimensional Array)

In [1]:
# de facto standard
import numpy as np

In [2]:
a = np.array([1,4,6,8], float)   # 데이터가 object로 옴
print(a) 

[1. 4. 6. 8.]


In [3]:
# a 인덱싱
a[3], a.dtype, a.shape
# float62 : 기본 실수 값이 / 4, 표현된 이유 : 1차원을 튜플로 표현되어서

(8.0, dtype('float64'), (4,))

## 2. Array shape

In [4]:
# 1차원 - vector
a = np.array([1,4,5,8], float)

In [6]:
# 2차원 - matrix
m = [[1,4], [5,8]]
b = np.array(m, float)
print(b)

[[1. 4.]
 [5. 8.]]


In [9]:
# 3차원 - tensor
t = [[[1,4], [5,8]], [[11,14], [15,18]]]
c = np.array(t, float)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]])

In [10]:
a.shape, b.shape, c.shape

((4,), (2, 2), (2, 2, 2))

In [11]:
# ndim
a.ndim, b.ndim, c.ndim

(1, 2, 3)

In [12]:
# size
a.size, b.size, c.size

(4, 4, 8)