# Numpy - Numerical Python

## 1. ndarray(Numpy Dimensional Array)

In [14]:
# de facto standard
import numpy as np

In [15]:
a = np.array([1,4,6,8], float)   # 데이터가 object로 옴
print(a) 

[1. 4. 6. 8.]


In [3]:
# a 인덱싱
a[3], a.dtype, a.shape
# float62 : 기본 실수 값이 / 4, 표현된 이유 : 1차원을 튜플로 표현되어서

(8.0, dtype('float64'), (4,))

## 2. Array shape

In [4]:
# 1차원 - vector
a = np.array([1,4,5,8], float)

In [6]:
# 2차원 - matrix
m = [[1,4], [5,8]]
b = np.array(m, float)
print(b)

[[1. 4.]
 [5. 8.]]


In [9]:
# 3차원 - tensor
t = [[[1,4], [5,8]], [[11,14], [15,18]]]
c = np.array(t, float)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]])

In [10]:
a.shape, b.shape, c.shape

((4,), (2, 2), (2, 2, 2))

In [11]:
# ndim
a.ndim, b.ndim, c.ndim

(1, 2, 3)

In [12]:
# size
a.size, b.size, c.size

(4, 4, 8)

In [18]:
# data type(dtype)
c = np.array(t, dtype=np.float32)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]], dtype=float32)

## - reshape: size 동일

In [17]:
c.reshape(2,4).shape

(2, 4)

In [19]:
c.reshape(2,4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]], dtype=float32)

In [20]:
c.reshape(8,)

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.], dtype=float32)

In [21]:
#-1은 한번에 가능
c.reshape(-1,4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]], dtype=float32)

In [23]:
# flatten - 1차원으로 변환
c.flatten()

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.], dtype=float32)

## 3. Indexing and Slicing

In [25]:
a=np.arange(6)

In [26]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
# 리스트 1차원     numpy 1차원
a[0][1]             a[0.1]

1

In [28]:
a[:, :2]

array([[0, 1],
       [3, 4]])

In [30]:
b = np.arange(16).reshape(-1,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
# 5,6,9.10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [35]:
# 0,1,4,5,8,9
b[:3, :2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [37]:
# 세번째 열까지는 x, 마지막 열은 y
x, y = b[:, :-1], b[:,-1]
x.shape, y.shape

((4, 3), (4,))

## 4. Creation

In [38]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(0,1.1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [42]:
# list로 만들기 위해 .tolist()
np.arange(0,1.1,0.1).tolist()

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0]

In [43]:
np.arange(0,1.1,0.1).tolist()[3] == 0.3

False

In [44]:
# 두 실수의 비교는 차이가 아주 작냐를 물어보는 것이 올바른 방법
np.abs(np.arange(0,1.1,0.1).tolist()[3] - 0.3) < 1e-8

True

In [45]:
# ones, zeros, empty
a = np.zeros((5,), dtype=np.int8)  # (5) x -> (5,) 써야 튜플값으로 들어감
a

array([0, 0, 0, 0, 0], dtype=int8)

In [46]:
b = np.ones((2,4), dtype = np.int8)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [47]:
np.empty((2,5))

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ]])

In [48]:
a = np.arange(24).reshape(4,-1)
np.ones_like(a)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [49]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [50]:
# 단위 행렬: identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
# eye - 대각선이 1인 행렬
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [52]:
np.eye(n=3,m=5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [53]:
np.eye(3,5,2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## - Random sampling
##  [참고] https://rfriend.tistory.com/284

In [54]:
np.random.seed(2021)

# 균등 분포(low, high, size)
np.random.uniform(0,1,10).reshape(2,5)

array([[0.60597828, 0.73336936, 0.13894716, 0.31267308, 0.99724328],
       [0.12816238, 0.17899311, 0.75292543, 0.66216051, 0.78431013]])

In [55]:
# normal: 정규분포(loc, scale, size)
np.random.normal(0,1,10).reshape(2,5)

array([[ 0.10641374,  0.42215483,  0.12420684, -0.83795346,  0.4090157 ],
       [ 0.10275122, -1.90772239,  1.1002243 , -1.40232506, -0.22508127]])

In [56]:
# 이항분포, 포아송분포, t-분포, f-분포
np.random.binomial(100, 1/6., 10)

array([17, 13, 17, 16, 17, 20, 19, 11, 18, 18])