## 5. Operation
## [참고(axis part)] http://taewan.kim/post/numpy_sum_axis/

In [1]:
import numpy as np

In [2]:
a = np.arange(1,11,dtype=np.float32)
a.sum()

55.0

In [3]:
b = np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
b.sum()

78

In [4]:
# 세로 방향의 합
b.sum(axis=0)

array([15, 18, 21, 24])

In [6]:
# 가로 방향의 합
b.sum(axis=1)

array([10, 26, 42])

In [7]:
# 평균
b.mean(axis=0), b.mean(axis=1)

(array([5., 6., 7., 8.]), array([ 2.5,  6.5, 10.5]))

In [8]:
# 표준편차
b.std(axis=0), b.std(axis=1)

(array([3.26598632, 3.26598632, 3.26598632, 3.26598632]),
 array([1.11803399, 1.11803399, 1.11803399]))

In [9]:
# 수학 함수
x = np.arange(-1.,1.01, 0.01)
x.size

201

## Sigmoid 함수
## 인공신경망 활성함수 중 하나로, step fuction->디지털 신호/sigmoid->아날로그
## 인자값에 1 / (1+ e^-x)라는 수식을 대입. 자연상수 e를 사용해 0~1이라는 값 사이에 완만한 그라데이션을 준 것이 특징.


In [51]:
import numpy as np
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [47]:
# sigmoid 함수
y = 1./(1. + np.exp(-x))

## - Concatenate

In [12]:
a = np.arange(1,5).reshape(2,2)
b = np.array([[5,6]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
# 전치행렬(transpose)
b.T

array([[5],
       [6]])

In [15]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [17]:
np.hstack((a, b.T))

array([[1, 2, 5],
       [3, 4, 6]])

## - Array operation

In [18]:
# element-wise operation
a -a

array([[0, 0],
       [0, 0]])

In [19]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [21]:
a / a

array([[1., 1.],
       [1., 1.]])

## - dot product

In [22]:
a = np.arange(1,7).reshape(2,3)
a.dot(a.T)

array([[14, 32],
       [32, 77]])

In [23]:
np.dot(a, a.T)

array([[14, 32],
       [32, 77]])

## - Broadcasting

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a + 10  # 10이라는 스칼라 값이 a matrix에 전체적으로 펼쳐짐

array([[11, 12, 13],
       [14, 15, 16]])

In [25]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [26]:
a **2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [27]:
a + np.array([10,20,30])

array([[11, 22, 33],
       [14, 25, 36]])

## 7. Comparison

In [30]:
a = np.arange(5)
np.all(a), np.any(a)

(False, True)

In [31]:
a > 2

array([False, False, False,  True,  True])

In [32]:
a[a>2]

array([3, 4])

## - Logical operation

In [33]:
a = np.arange(5)
b = np.logical_and(a>0, a<3)
b

array([False,  True,  True, False, False])

In [37]:
c = np.logical_not(b)
c

array([ True, False, False,  True,  True])

In [38]:
np.logical_or(b,c)

array([ True,  True,  True,  True,  True])

In [39]:
np.logical_xor(b,c)

array([ True,  True,  True,  True,  True])

In [40]:
a = np.arange(5)
np.where(a>2)

(array([3, 4], dtype=int64),)

## - NaN(Not a Number), Int(Infinite)

In [41]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [42]:
np.isnan(a),np.isfinite(a)

(array([False,  True, False]), array([ True, False, False]))

## -argmax, argmin

In [52]:
a = np.arange(6)
np.argmax(a), np.argmin(a)

(5, 0)

In [53]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
np.argmin(b, axis=0)

array([0, 0, 0, 0], dtype=int64)

In [55]:
np.argmin(b, axis=1)

array([0, 0, 0], dtype=int64)