In [2]:
import numpy as np 

## 08. Boolean and Fancy Index

In [4]:
np.random.seed(2021)
a = np.random.uniform(1,10,4)
a

array([6.45380451, 7.60032425, 2.25052441, 3.81405775])

In [5]:
a > 3

array([ True,  True, False,  True])

In [6]:
# Boolean indexing : a에서 조건을 줘서 true인 데이터만 추출
a[a>3]

array([6.45380451, 7.60032425, 3.81405775])

## - Fancy index

In [7]:
a = np.arange(1, 5) * 2
a

array([2, 4, 6, 8])

In [8]:
b = np.array([0,1,3,2,1,3])
a[b]

array([2, 4, 8, 6, 4, 8])

In [10]:
a = np.arange(8).reshape(2,4)

In [11]:
b = np.array([0,0,1,1,0])
c = np.array([0,2,3,1,2])
a[b,c]

array([0, 2, 7, 5, 2])