In [1]:
import numpy as np

# 1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.
##     10 20 30 40
##     50 60 70 80

In [2]:
a = np.array([(10, 20, 30, 40), (50, 60, 70, 80)])
print(a)

[[10 20 30 40]
 [50 60 70 80]]


# 2. 다음 행렬과 같은 행렬이 있다.
## m = np.array([[ 0, 1, 2, 3, 4],
## [ 5, 6, 7, 8, 9],
## [10, 11, 12, 13, 14]])
 1) 이 행렬에서 값 7 을 인덱싱한다.
 2) 이 행렬에서 값 14 을 인덱싱한다.
 3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
 4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
 5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [3]:
m = np.array([[ 0, 1, 2, 3, 4], [ 5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
print(m)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## 1) 이 행렬에서 값 7 을 인덱싱한다.

In [4]:
np.where(m == 7)

(array([1], dtype=int64), array([2], dtype=int64))

In [13]:
m[1,2]

7

## 2) 이 행렬에서 값 14 을 인덱싱한다.

In [5]:
np.where(m == 14)

(array([2], dtype=int64), array([4], dtype=int64))

In [14]:
m[2,4]

14

## 3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.

In [15]:
m[1,1:3]

array([6, 7])

## 4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.

In [18]:
m[1:,2]

array([ 7, 12])

## 5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [24]:
m[0:2 , 3:5]

array([[3, 4],
       [8, 9]])

# 3. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.
1) 이 배열에서 3의 배수를 찾아라.
2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

## Numpy 다차원 배열을 1차원으로 변환시킬 수 있는 함수 존재 - reave(), reshape(), flatten()

In [29]:
# 3x5 형태를 가진 2차원 벡터
m.shape

(3, 5)

In [32]:
# size 동일 -> reshape 변환 가능
m2 = m.reshape(-1)
m2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 1) 이 배열에서 3의 배수를 찾아라.

In [35]:
m2[m2 % 3 == 0]

array([ 0,  3,  6,  9, 12])

## 2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.

In [36]:
m2[m2 % 4 == 1]

array([ 1,  5,  9, 13])

## 3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [44]:
m2[(m2 % 3 == 0) & (m2 % 4 == 1)]

array([9])

# 4. 값을 직접 입력하지 말고 우측의 행렬을 만드시오. 

In [ ]:
np.identity(3)

# 5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에
대해 다음과 같은 값을 구하시오.
1) 전체의 최댓값
2) 각 행의 합
3) 각 행의 최댓값
4) 각 열의 평균
5) 각 열의 최솟값

## -random(난수 생성 라이브러리): 0이상 1미만의 수중 랜덤한 값을 return
## -random.randrange(0,10): 범위지정 난수생성 함수기능
## -random.randint(0,10): randrange와 동일하게 범위지정 가능하며 정수값 return

In [70]:
# 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬
mr = np.random.choice(range(0,10),30).reshape(5,6)
mr

array([[7, 5, 9, 9, 3, 8],
       [1, 0, 2, 4, 9, 6],
       [8, 0, 2, 9, 0, 2],
       [4, 7, 4, 2, 4, 5],
       [9, 5, 1, 7, 9, 5]])

## 1) 전체의 최댓값

In [63]:
np.max(mr)

9

## 2) 각 행의 합

In [67]:
mr.sum(axis=1)/6

array([4.16666667, 6.        , 3.5       , 4.66666667, 3.83333333])

## 3) 각 행의 최댓값

In [69]:
np.max(mr, axis = 1)

array([9, 9, 8, 9, 8])

## 4) 각 열의 평균

In [68]:
mr.sum(axis=0)/5

array([5.6, 8. , 2.4, 3.2, 3. , 4.4])

## 5) 각 열의 최솟값

In [64]:
np.min(mr)

0

# 6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.

In [72]:
mt = np.array([[ 1, 2, 3, 4],[ 46, 99, 100, 71],[ 81, 59, 90, 100]])
mt

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [75]:
a = mt[mt[:, 1].argsort()]
a

array([[  1,   2,   3,   4],
       [ 81,  59,  90, 100],
       [ 46,  99, 100,  71]])